DROP TABLE IF EXISTS CREDENZIALI_GRUPPO;
DROP TABLE IF EXISTS USERGROUP;
DROP TABLE IF EXISTS GRUPPO;
DROP TABLE IF EXISTS CREDENZIALI;
DROP TABLE IF EXISTS BUSINESS;
DROP TABLE IF EXISTS PREMIUM;
DROP TABLE IF EXISTS UTENTE;
DROP TABLE IF EXISTS DOMINIO;

CREATE TABLE UTENTE
(
    ID_USER         INTEGER PRIMARY KEY AUTOINCREMENT,
    NOME            VARCHAR(40) NOT NULL,
    COGNOME         VARCHAR(40) NOT NULL,
    USERNAME        VARCHAR(20) NOT NULL UNIQUE,
    EMAIL           VARCHAR(40) NOT NULL UNIQUE,
    N_TEL           VARCHAR(40) NOT NULL,
    DATA_DI_NASCITA DATE NULL,
    IMMAGINE        BLOB DEFAULT NULL,
    PASSWORD        VARCHAR(40) NOT NULL
);

CREATE TABLE PREMIUM
(
    ID_PREMIUM  INTEGER PRIMARY KEY,
    DATA_INIZIO DATE          NOT NULL,
    PREZZO      NUMERIC(5, 2) NOT NULL,
    FOREIGN KEY (ID_PREMIUM) REFERENCES UTENTE (ID_USER) ON DELETE CASCADE
);

CREATE TABLE BUSINESS
(
    ID_BUSINESS INTEGER PRIMARY KEY,
    DATA_INIZIO DATE          NOT NULL,
    PREZZO      NUMERIC(5, 2) NOT NULL,
    FOREIGN KEY (ID_BUSINESS) REFERENCES UTENTE (ID_USER) ON DELETE CASCADE
);

CREATE TABLE GRUPPO
(
    ID_GRUPPO   INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_ADMIN    INTEGER NOT NULL,
    NOME_GRUPPO VARCHAR(40) DEFAULT 'GRUPPO',
    FOREIGN KEY (ID_ADMIN) REFERENCES BUSINESS (ID_BUSINESS) ON DELETE CASCADE
);

CREATE TABLE USERGROUP
(
    ID_UG    INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_US    INTEGER NOT NULL,
    ID_GROUP INTEGER NOT NULL,
    FOREIGN KEY (ID_US) REFERENCES UTENTE (ID_USER) ON DELETE CASCADE,
    FOREIGN KEY (ID_GROUP) REFERENCES GRUPPO (ID_GRUPPO) ON DELETE CASCADE,
    UNIQUE (ID_GROUP, ID_US)

);

CREATE TABLE CREDENZIALI
(
    ID_CRED       INTEGER PRIMARY KEY AUTOINCREMENT,
    TITOLO        VARCHAR(20),
    EMAIL_CRED    VARCHAR(40) NOT NULL,
    PASSWORD_CRED VARCHAR(40) NOT NULL,
    URL           VARCHAR(100),
    NOTE          TEXT,
    ID_UTENTE     INTEGER     NOT NULL,
    FOREIGN KEY (ID_UTENTE) REFERENCES UTENTE (ID_USER) ON DELETE CASCADE
);

CREATE TABLE CREDENZIALI_GRUPPO
(
    ID_CREDG       INTEGER PRIMARY KEY AUTOINCREMENT,
    TIT_GROUP      VARCHAR(20),
    EMAIL_GROUP    VARCHAR(40) NOT NULL,
    PASSWORD_GROUP VARCHAR(40) NOT NULL,
    URL_GROUP      VARCHAR(100),
    NOTE_GROUP     TEXT,
    ID_GR          INTEGER     NOT NULL,
    FOREIGN KEY (ID_GR) REFERENCES GRUPPO (ID_GRUPPO) ON DELETE CASCADE
);
